server:
  context-path: /application-service
  port: 7000

spring:
  datasource:
      platform: POSTGRESQL
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://174.138.9.118:5432/kris5
      username: kris5
      password: 123Kris5Test

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false


eureka:
  client:
    serviceUrl:
      defaultZone: http://167.99.33.74:8761/eureka/