//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ariregistri_toimik_Request complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ariregistri_toimik_Request"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ariregistri_kood" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="keel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="formaat" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}x_formaat" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ariregistri_toimik_Request", propOrder = {
    "ariregistriKood",
    "keel",
    "formaat"
})
public class AriregistriToimikRequest {

    @XmlElement(name = "ariregistri_kood")
    protected int ariregistriKood;
    @XmlElementRef(name = "keel", type = JAXBElement.class, required = false)
    protected JAXBElement<java.lang.String> keel;
    @XmlElementRef(name = "formaat", type = JAXBElement.class, required = false)
    protected JAXBElement<ee.rik.kris5.xroad.model.soap.XFormaat> formaat;

    /**
     * Gets the value of the ariregistriKood property.
     * 
     */
    public int getAriregistriKood() {
        return ariregistriKood;
    }

    /**
     * Sets the value of the ariregistriKood property.
     * 
     */
    public void setAriregistriKood(int value) {
        this.ariregistriKood = value;
    }

    /**
     * Gets the value of the keel property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}
     *     
     */
    public JAXBElement<java.lang.String> getKeel() {
        return keel;
    }

    /**
     * Sets the value of the keel property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}
     *     
     */
    public void setKeel(JAXBElement<java.lang.String> value) {
        this.keel = value;
    }

    /**
     * Gets the value of the formaat property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XFormaat }{@code >}
     *     
     */
    public JAXBElement<XFormaat> getFormaat() {
        return formaat;
    }

    /**
     * Sets the value of the formaat property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XFormaat }{@code >}
     *     
     */
    public void setFormaat(JAXBElement<XFormaat> value) {
        this.formaat = value;
    }

}
