//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for detailandmed_v4_dokument_maarus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="detailandmed_v4_dokument_maarus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="maaruse_id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="maaruse_nr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="maaruse_kpv" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="maaruse_liik" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="maaruse_liik_tekstina" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="maaruse_olek" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="maaruse_olek_tekstina" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="kande_joustumise_kpv_voi_maaruse_lisatahtaeg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="kandeliik" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="kandeliik_tekstina" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "detailandmed_v4_dokument_maarus", propOrder = {
    "maaruseId",
    "maaruseNr",
    "maaruseKpv",
    "maaruseLiik",
    "maaruseLiikTekstina",
    "maaruseOlek",
    "maaruseOlekTekstina",
    "kandeJoustumiseKpvVoiMaaruseLisatahtaeg",
    "kandeliik",
    "kandeliikTekstina"
})
public class DetailandmedV4DokumentMaarus {

    @XmlElement(name = "maaruse_id")
    protected BigInteger maaruseId;
    @XmlElement(name = "maaruse_nr")
    protected java.lang.String maaruseNr;
    @XmlElement(name = "maaruse_kpv")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar maaruseKpv;
    @XmlElement(name = "maaruse_liik")
    protected java.lang.String maaruseLiik;
    @XmlElement(name = "maaruse_liik_tekstina")
    protected java.lang.String maaruseLiikTekstina;
    @XmlElement(name = "maaruse_olek")
    protected java.lang.String maaruseOlek;
    @XmlElement(name = "maaruse_olek_tekstina")
    protected java.lang.String maaruseOlekTekstina;
    @XmlElement(name = "kande_joustumise_kpv_voi_maaruse_lisatahtaeg")
    protected java.lang.String kandeJoustumiseKpvVoiMaaruseLisatahtaeg;
    protected java.lang.String kandeliik;
    @XmlElement(name = "kandeliik_tekstina")
    protected java.lang.String kandeliikTekstina;

    /**
     * Gets the value of the maaruseId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaaruseId() {
        return maaruseId;
    }

    /**
     * Sets the value of the maaruseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaaruseId(BigInteger value) {
        this.maaruseId = value;
    }

    /**
     * Gets the value of the maaruseNr property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getMaaruseNr() {
        return maaruseNr;
    }

    /**
     * Sets the value of the maaruseNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setMaaruseNr(java.lang.String value) {
        this.maaruseNr = value;
    }

    /**
     * Gets the value of the maaruseKpv property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMaaruseKpv() {
        return maaruseKpv;
    }

    /**
     * Sets the value of the maaruseKpv property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMaaruseKpv(XMLGregorianCalendar value) {
        this.maaruseKpv = value;
    }

    /**
     * Gets the value of the maaruseLiik property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getMaaruseLiik() {
        return maaruseLiik;
    }

    /**
     * Sets the value of the maaruseLiik property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setMaaruseLiik(java.lang.String value) {
        this.maaruseLiik = value;
    }

    /**
     * Gets the value of the maaruseLiikTekstina property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getMaaruseLiikTekstina() {
        return maaruseLiikTekstina;
    }

    /**
     * Sets the value of the maaruseLiikTekstina property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setMaaruseLiikTekstina(java.lang.String value) {
        this.maaruseLiikTekstina = value;
    }

    /**
     * Gets the value of the maaruseOlek property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getMaaruseOlek() {
        return maaruseOlek;
    }

    /**
     * Sets the value of the maaruseOlek property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setMaaruseOlek(java.lang.String value) {
        this.maaruseOlek = value;
    }

    /**
     * Gets the value of the maaruseOlekTekstina property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getMaaruseOlekTekstina() {
        return maaruseOlekTekstina;
    }

    /**
     * Sets the value of the maaruseOlekTekstina property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setMaaruseOlekTekstina(java.lang.String value) {
        this.maaruseOlekTekstina = value;
    }

    /**
     * Gets the value of the kandeJoustumiseKpvVoiMaaruseLisatahtaeg property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getKandeJoustumiseKpvVoiMaaruseLisatahtaeg() {
        return kandeJoustumiseKpvVoiMaaruseLisatahtaeg;
    }

    /**
     * Sets the value of the kandeJoustumiseKpvVoiMaaruseLisatahtaeg property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setKandeJoustumiseKpvVoiMaaruseLisatahtaeg(java.lang.String value) {
        this.kandeJoustumiseKpvVoiMaaruseLisatahtaeg = value;
    }

    /**
     * Gets the value of the kandeliik property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getKandeliik() {
        return kandeliik;
    }

    /**
     * Sets the value of the kandeliik property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setKandeliik(java.lang.String value) {
        this.kandeliik = value;
    }

    /**
     * Gets the value of the kandeliikTekstina property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getKandeliikTekstina() {
        return kandeliikTekstina;
    }

    /**
     * Sets the value of the kandeliikTekstina property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setKandeliikTekstina(java.lang.String value) {
        this.kandeliikTekstina = value;
    }

}
