//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for detailandmed_v4_ettevotja complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="detailandmed_v4_ettevotja"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ariregistri_kood" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="yldandmed" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}detailandmed_v4_yldandmed" minOccurs="0"/&gt;
 *         &lt;element name="isikuandmed" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}detailandmed_v4_isikuandmed" minOccurs="0"/&gt;
 *         &lt;element name="kommertspandiandmed" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}detailandmed_kommertspandiandmed" minOccurs="0"/&gt;
 *         &lt;element name="menetluses_avaldused" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}detailandmed_v4_dokumendid" minOccurs="0"/&gt;
 *         &lt;element name="maarused" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}detailandmed_maarused" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "detailandmed_v4_ettevotja", propOrder = {
    "ariregistriKood",
    "yldandmed",
    "isikuandmed",
    "kommertspandiandmed",
    "menetlusesAvaldused",
    "maarused"
})
public class DetailandmedV4Ettevotja {

    @XmlElement(name = "ariregistri_kood")
    protected int ariregistriKood;
    protected DetailandmedV4Yldandmed yldandmed;
    protected DetailandmedV4Isikuandmed isikuandmed;
    protected DetailandmedKommertspandiandmed kommertspandiandmed;
    @XmlElement(name = "menetluses_avaldused")
    protected DetailandmedV4Dokumendid menetlusesAvaldused;
    protected DetailandmedMaarused maarused;

    /**
     * Gets the value of the ariregistriKood property.
     * 
     */
    public int getAriregistriKood() {
        return ariregistriKood;
    }

    /**
     * Sets the value of the ariregistriKood property.
     * 
     */
    public void setAriregistriKood(int value) {
        this.ariregistriKood = value;
    }

    /**
     * Gets the value of the yldandmed property.
     * 
     * @return
     *     possible object is
     *     {@link DetailandmedV4Yldandmed }
     *     
     */
    public DetailandmedV4Yldandmed getYldandmed() {
        return yldandmed;
    }

    /**
     * Sets the value of the yldandmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetailandmedV4Yldandmed }
     *     
     */
    public void setYldandmed(DetailandmedV4Yldandmed value) {
        this.yldandmed = value;
    }

    /**
     * Gets the value of the isikuandmed property.
     * 
     * @return
     *     possible object is
     *     {@link DetailandmedV4Isikuandmed }
     *     
     */
    public DetailandmedV4Isikuandmed getIsikuandmed() {
        return isikuandmed;
    }

    /**
     * Sets the value of the isikuandmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetailandmedV4Isikuandmed }
     *     
     */
    public void setIsikuandmed(DetailandmedV4Isikuandmed value) {
        this.isikuandmed = value;
    }

    /**
     * Gets the value of the kommertspandiandmed property.
     * 
     * @return
     *     possible object is
     *     {@link DetailandmedKommertspandiandmed }
     *     
     */
    public DetailandmedKommertspandiandmed getKommertspandiandmed() {
        return kommertspandiandmed;
    }

    /**
     * Sets the value of the kommertspandiandmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetailandmedKommertspandiandmed }
     *     
     */
    public void setKommertspandiandmed(DetailandmedKommertspandiandmed value) {
        this.kommertspandiandmed = value;
    }

    /**
     * Gets the value of the menetlusesAvaldused property.
     * 
     * @return
     *     possible object is
     *     {@link DetailandmedV4Dokumendid }
     *     
     */
    public DetailandmedV4Dokumendid getMenetlusesAvaldused() {
        return menetlusesAvaldused;
    }

    /**
     * Sets the value of the menetlusesAvaldused property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetailandmedV4Dokumendid }
     *     
     */
    public void setMenetlusesAvaldused(DetailandmedV4Dokumendid value) {
        this.menetlusesAvaldused = value;
    }

    /**
     * Gets the value of the maarused property.
     * 
     * @return
     *     possible object is
     *     {@link DetailandmedMaarused }
     *     
     */
    public DetailandmedMaarused getMaarused() {
        return maarused;
    }

    /**
     * Sets the value of the maarused property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetailandmedMaarused }
     *     
     */
    public void setMaarused(DetailandmedMaarused value) {
        this.maarused = value;
    }

}
