//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for esindusoigusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="esindusoigusType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tegevus" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}x_tegevus"/&gt;
 *         &lt;element name="roll" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}x_isikuroll" minOccurs="0"/&gt;
 *         &lt;element name="liik" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}x_esindustyyp" minOccurs="0"/&gt;
 *         &lt;element name="kirjeldus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "esindusoigusType", propOrder = {
    "tegevus",
    "roll",
    "liik",
    "kirjeldus"
})
public class EsindusoigusType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected XTegevus tegevus;
    @XmlSchemaType(name = "string")
    protected XIsikuroll roll;
    @XmlSchemaType(name = "string")
    protected XEsindustyyp liik;
    @XmlElement(required = true)
    protected java.lang.String kirjeldus;

    /**
     * Gets the value of the tegevus property.
     * 
     * @return
     *     possible object is
     *     {@link XTegevus }
     *     
     */
    public XTegevus getTegevus() {
        return tegevus;
    }

    /**
     * Sets the value of the tegevus property.
     * 
     * @param value
     *     allowed object is
     *     {@link XTegevus }
     *     
     */
    public void setTegevus(XTegevus value) {
        this.tegevus = value;
    }

    /**
     * Gets the value of the roll property.
     * 
     * @return
     *     possible object is
     *     {@link XIsikuroll }
     *     
     */
    public XIsikuroll getRoll() {
        return roll;
    }

    /**
     * Sets the value of the roll property.
     * 
     * @param value
     *     allowed object is
     *     {@link XIsikuroll }
     *     
     */
    public void setRoll(XIsikuroll value) {
        this.roll = value;
    }

    /**
     * Gets the value of the liik property.
     * 
     * @return
     *     possible object is
     *     {@link XEsindustyyp }
     *     
     */
    public XEsindustyyp getLiik() {
        return liik;
    }

    /**
     * Sets the value of the liik property.
     * 
     * @param value
     *     allowed object is
     *     {@link XEsindustyyp }
     *     
     */
    public void setLiik(XEsindustyyp value) {
        this.liik = value;
    }

    /**
     * Gets the value of the kirjeldus property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getKirjeldus() {
        return kirjeldus;
    }

    /**
     * Sets the value of the kirjeldus property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setKirjeldus(java.lang.String value) {
        this.kirjeldus = value;
    }

}
