//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ettevotja_muudatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ettevotja_muudatus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ariregistri_kood" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="arinimi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="oiguslik_vorm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="kandevalised_isikud" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="kandevalised_sidevahendid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="kandevalised_tegevusalad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="kanded" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}ettevotja_muudatuse_kanne" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ettevotja_muudatus", propOrder = {
    "ariregistriKood",
    "arinimi",
    "oiguslikVorm",
    "kandevalisedIsikud",
    "kandevalisedSidevahendid",
    "kandevalisedTegevusalad",
    "kanded"
})
public class EttevotjaMuudatus {

    @XmlElement(name = "ariregistri_kood")
    protected java.lang.Integer ariregistriKood;
    protected java.lang.String arinimi;
    @XmlElement(name = "oiguslik_vorm")
    protected java.lang.String oiguslikVorm;
    @XmlElement(name = "kandevalised_isikud")
    protected java.lang.String kandevalisedIsikud;
    @XmlElement(name = "kandevalised_sidevahendid")
    protected java.lang.String kandevalisedSidevahendid;
    @XmlElement(name = "kandevalised_tegevusalad")
    protected java.lang.String kandevalisedTegevusalad;
    protected List<EttevotjaMuudatuseKanne> kanded;

    /**
     * Gets the value of the ariregistriKood property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Integer }
     *     
     */
    public java.lang.Integer getAriregistriKood() {
        return ariregistriKood;
    }

    /**
     * Sets the value of the ariregistriKood property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Integer }
     *     
     */
    public void setAriregistriKood(java.lang.Integer value) {
        this.ariregistriKood = value;
    }

    /**
     * Gets the value of the arinimi property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getArinimi() {
        return arinimi;
    }

    /**
     * Sets the value of the arinimi property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setArinimi(java.lang.String value) {
        this.arinimi = value;
    }

    /**
     * Gets the value of the oiguslikVorm property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getOiguslikVorm() {
        return oiguslikVorm;
    }

    /**
     * Sets the value of the oiguslikVorm property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setOiguslikVorm(java.lang.String value) {
        this.oiguslikVorm = value;
    }

    /**
     * Gets the value of the kandevalisedIsikud property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getKandevalisedIsikud() {
        return kandevalisedIsikud;
    }

    /**
     * Sets the value of the kandevalisedIsikud property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setKandevalisedIsikud(java.lang.String value) {
        this.kandevalisedIsikud = value;
    }

    /**
     * Gets the value of the kandevalisedSidevahendid property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getKandevalisedSidevahendid() {
        return kandevalisedSidevahendid;
    }

    /**
     * Sets the value of the kandevalisedSidevahendid property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setKandevalisedSidevahendid(java.lang.String value) {
        this.kandevalisedSidevahendid = value;
    }

    /**
     * Gets the value of the kandevalisedTegevusalad property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getKandevalisedTegevusalad() {
        return kandevalisedTegevusalad;
    }

    /**
     * Sets the value of the kandevalisedTegevusalad property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setKandevalisedTegevusalad(java.lang.String value) {
        this.kandevalisedTegevusalad = value;
    }

    /**
     * Gets the value of the kanded property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kanded property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKanded().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EttevotjaMuudatuseKanne }
     * 
     * 
     */
    public List<EttevotjaMuudatuseKanne> getKanded() {
        if (kanded == null) {
            kanded = new ArrayList<EttevotjaMuudatuseKanne>();
        }
        return this.kanded;
    }

}
