//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ettevotja_muudatused_tasuline_vastus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ettevotja_muudatused_tasuline_vastus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ettevotja_muudatused" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}ettevotja_muudatus" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="tulemuste_arv" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ettevotja_muudatused_tasuline_vastus", propOrder = {
    "ettevotjaMuudatused",
    "tulemusteArv"
})
public class EttevotjaMuudatusedTasulineVastus {

    @XmlElement(name = "ettevotja_muudatused")
    protected List<EttevotjaMuudatus> ettevotjaMuudatused;
    @XmlElement(name = "tulemuste_arv")
    protected java.lang.Integer tulemusteArv;

    /**
     * Gets the value of the ettevotjaMuudatused property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ettevotjaMuudatused property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEttevotjaMuudatused().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EttevotjaMuudatus }
     * 
     * 
     */
    public List<EttevotjaMuudatus> getEttevotjaMuudatused() {
        if (ettevotjaMuudatused == null) {
            ettevotjaMuudatused = new ArrayList<EttevotjaMuudatus>();
        }
        return this.ettevotjaMuudatused;
    }

    /**
     * Gets the value of the tulemusteArv property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Integer }
     *     
     */
    public java.lang.Integer getTulemusteArv() {
        return tulemusteArv;
    }

    /**
     * Sets the value of the tulemusteArv property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Integer }
     *     
     */
    public void setTulemusteArv(java.lang.Integer value) {
        this.tulemusteArv = value;
    }

}
