//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ettevotja_muudatus_kanne complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ettevotja_muudatus_kanne"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ettevotja_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ettevotja_ariregistri_kood" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="ettevotja_arinimi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ettevotja_oiguslik_vorm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ettevotja_piirkond" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="ettevotja_uus_piirkond" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="registrikaardi_tyyp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="registrikaardi_nr" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="kande_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="kande_nr" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="kande_kpv" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="kande_liik" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="kande_liik_tekst" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="kande_staatuse_muutus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="kandeelement" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}ettevotja_muudatus_kandeelement" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ettevotja_muudatus_kanne", propOrder = {
    "ettevotjaId",
    "ettevotjaAriregistriKood",
    "ettevotjaArinimi",
    "ettevotjaOiguslikVorm",
    "ettevotjaPiirkond",
    "ettevotjaUusPiirkond",
    "registrikaardiTyyp",
    "registrikaardiNr",
    "kandeId",
    "kandeNr",
    "kandeKpv",
    "kandeLiik",
    "kandeLiikTekst",
    "kandeStaatuseMuutus",
    "kandeelement"
})
public class EttevotjaMuudatusKanne {

    @XmlElement(name = "ettevotja_id")
    protected java.lang.String ettevotjaId;
    @XmlElement(name = "ettevotja_ariregistri_kood")
    protected java.lang.Integer ettevotjaAriregistriKood;
    @XmlElement(name = "ettevotja_arinimi")
    protected java.lang.String ettevotjaArinimi;
    @XmlElement(name = "ettevotja_oiguslik_vorm")
    protected java.lang.String ettevotjaOiguslikVorm;
    @XmlElement(name = "ettevotja_piirkond")
    protected java.lang.Integer ettevotjaPiirkond;
    @XmlElement(name = "ettevotja_uus_piirkond")
    protected java.lang.Integer ettevotjaUusPiirkond;
    @XmlElement(name = "registrikaardi_tyyp")
    protected java.lang.String registrikaardiTyyp;
    @XmlElement(name = "registrikaardi_nr")
    protected java.lang.Integer registrikaardiNr;
    @XmlElement(name = "kande_id")
    protected java.lang.String kandeId;
    @XmlElement(name = "kande_nr")
    protected java.lang.Integer kandeNr;
    @XmlElement(name = "kande_kpv")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar kandeKpv;
    @XmlElement(name = "kande_liik")
    protected java.lang.Integer kandeLiik;
    @XmlElement(name = "kande_liik_tekst")
    protected java.lang.String kandeLiikTekst;
    @XmlElement(name = "kande_staatuse_muutus")
    protected java.lang.String kandeStaatuseMuutus;
    protected List<EttevotjaMuudatusKandeelement> kandeelement;

    /**
     * Gets the value of the ettevotjaId property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getEttevotjaId() {
        return ettevotjaId;
    }

    /**
     * Sets the value of the ettevotjaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setEttevotjaId(java.lang.String value) {
        this.ettevotjaId = value;
    }

    /**
     * Gets the value of the ettevotjaAriregistriKood property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Integer }
     *     
     */
    public java.lang.Integer getEttevotjaAriregistriKood() {
        return ettevotjaAriregistriKood;
    }

    /**
     * Sets the value of the ettevotjaAriregistriKood property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Integer }
     *     
     */
    public void setEttevotjaAriregistriKood(java.lang.Integer value) {
        this.ettevotjaAriregistriKood = value;
    }

    /**
     * Gets the value of the ettevotjaArinimi property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getEttevotjaArinimi() {
        return ettevotjaArinimi;
    }

    /**
     * Sets the value of the ettevotjaArinimi property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setEttevotjaArinimi(java.lang.String value) {
        this.ettevotjaArinimi = value;
    }

    /**
     * Gets the value of the ettevotjaOiguslikVorm property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getEttevotjaOiguslikVorm() {
        return ettevotjaOiguslikVorm;
    }

    /**
     * Sets the value of the ettevotjaOiguslikVorm property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setEttevotjaOiguslikVorm(java.lang.String value) {
        this.ettevotjaOiguslikVorm = value;
    }

    /**
     * Gets the value of the ettevotjaPiirkond property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Integer }
     *     
     */
    public java.lang.Integer getEttevotjaPiirkond() {
        return ettevotjaPiirkond;
    }

    /**
     * Sets the value of the ettevotjaPiirkond property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Integer }
     *     
     */
    public void setEttevotjaPiirkond(java.lang.Integer value) {
        this.ettevotjaPiirkond = value;
    }

    /**
     * Gets the value of the ettevotjaUusPiirkond property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Integer }
     *     
     */
    public java.lang.Integer getEttevotjaUusPiirkond() {
        return ettevotjaUusPiirkond;
    }

    /**
     * Sets the value of the ettevotjaUusPiirkond property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Integer }
     *     
     */
    public void setEttevotjaUusPiirkond(java.lang.Integer value) {
        this.ettevotjaUusPiirkond = value;
    }

    /**
     * Gets the value of the registrikaardiTyyp property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getRegistrikaardiTyyp() {
        return registrikaardiTyyp;
    }

    /**
     * Sets the value of the registrikaardiTyyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setRegistrikaardiTyyp(java.lang.String value) {
        this.registrikaardiTyyp = value;
    }

    /**
     * Gets the value of the registrikaardiNr property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Integer }
     *     
     */
    public java.lang.Integer getRegistrikaardiNr() {
        return registrikaardiNr;
    }

    /**
     * Sets the value of the registrikaardiNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Integer }
     *     
     */
    public void setRegistrikaardiNr(java.lang.Integer value) {
        this.registrikaardiNr = value;
    }

    /**
     * Gets the value of the kandeId property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getKandeId() {
        return kandeId;
    }

    /**
     * Sets the value of the kandeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setKandeId(java.lang.String value) {
        this.kandeId = value;
    }

    /**
     * Gets the value of the kandeNr property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Integer }
     *     
     */
    public java.lang.Integer getKandeNr() {
        return kandeNr;
    }

    /**
     * Sets the value of the kandeNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Integer }
     *     
     */
    public void setKandeNr(java.lang.Integer value) {
        this.kandeNr = value;
    }

    /**
     * Gets the value of the kandeKpv property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getKandeKpv() {
        return kandeKpv;
    }

    /**
     * Sets the value of the kandeKpv property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setKandeKpv(XMLGregorianCalendar value) {
        this.kandeKpv = value;
    }

    /**
     * Gets the value of the kandeLiik property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Integer }
     *     
     */
    public java.lang.Integer getKandeLiik() {
        return kandeLiik;
    }

    /**
     * Sets the value of the kandeLiik property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Integer }
     *     
     */
    public void setKandeLiik(java.lang.Integer value) {
        this.kandeLiik = value;
    }

    /**
     * Gets the value of the kandeLiikTekst property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getKandeLiikTekst() {
        return kandeLiikTekst;
    }

    /**
     * Sets the value of the kandeLiikTekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setKandeLiikTekst(java.lang.String value) {
        this.kandeLiikTekst = value;
    }

    /**
     * Gets the value of the kandeStaatuseMuutus property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getKandeStaatuseMuutus() {
        return kandeStaatuseMuutus;
    }

    /**
     * Sets the value of the kandeStaatuseMuutus property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setKandeStaatuseMuutus(java.lang.String value) {
        this.kandeStaatuseMuutus = value;
    }

    /**
     * Gets the value of the kandeelement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kandeelement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKandeelement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EttevotjaMuudatusKandeelement }
     * 
     * 
     */
    public List<EttevotjaMuudatusKandeelement> getKandeelement() {
        if (kandeelement == null) {
            kandeelement = new ArrayList<EttevotjaMuudatusKandeelement>();
        }
        return this.kandeelement;
    }

}
