//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Hooneühist liikmesusei jagunemine - massiivi elemendi tüüp
 * 
 * <p>Java class for hy_liikmesusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hy_liikmesusType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="pindala" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="maksumaar" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}murdType" minOccurs="0"/&gt;
 *         &lt;element name="hy_kitsend" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}sooritakanne_hykitsendusedTypeArray" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hy_liikmesusType", propOrder = {
    "number",
    "pindala",
    "maksumaar",
    "hyKitsend"
})
public class HyLiikmesusType {

    protected int number;
    protected BigDecimal pindala;
    protected MurdType maksumaar;
    @XmlElement(name = "hy_kitsend")
    protected SooritakanneHykitsendusedTypeArray hyKitsend;

    /**
     * Gets the value of the number property.
     * 
     */
    public int getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     */
    public void setNumber(int value) {
        this.number = value;
    }

    /**
     * Gets the value of the pindala property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPindala() {
        return pindala;
    }

    /**
     * Sets the value of the pindala property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPindala(BigDecimal value) {
        this.pindala = value;
    }

    /**
     * Gets the value of the maksumaar property.
     * 
     * @return
     *     possible object is
     *     {@link MurdType }
     *     
     */
    public MurdType getMaksumaar() {
        return maksumaar;
    }

    /**
     * Sets the value of the maksumaar property.
     * 
     * @param value
     *     allowed object is
     *     {@link MurdType }
     *     
     */
    public void setMaksumaar(MurdType value) {
        this.maksumaar = value;
    }

    /**
     * Gets the value of the hyKitsend property.
     * 
     * @return
     *     possible object is
     *     {@link SooritakanneHykitsendusedTypeArray }
     *     
     */
    public SooritakanneHykitsendusedTypeArray getHyKitsend() {
        return hyKitsend;
    }

    /**
     * Sets the value of the hyKitsend property.
     * 
     * @param value
     *     allowed object is
     *     {@link SooritakanneHykitsendusedTypeArray }
     *     
     */
    public void setHyKitsend(SooritakanneHykitsendusedTypeArray value) {
        this.hyKitsend = value;
    }

}
