//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for kapitaliOmanikType_v3 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="kapitaliOmanikType_v3"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="isikud" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}isikType_v3" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="osa" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}murdType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "kapitaliOmanikType_v3", propOrder = {
    "isikud",
    "osa"
})
public class KapitaliOmanikTypeV3 {

    @XmlElement(nillable = true)
    protected List<IsikTypeV3> isikud;
    protected MurdType osa;

    /**
     * Gets the value of the isikud property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isikud property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIsikud().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IsikTypeV3 }
     * 
     * 
     */
    public List<IsikTypeV3> getIsikud() {
        if (isikud == null) {
            isikud = new ArrayList<IsikTypeV3>();
        }
        return this.isikud;
    }

    /**
     * Gets the value of the osa property.
     * 
     * @return
     *     possible object is
     *     {@link MurdType }
     *     
     */
    public MurdType getOsa() {
        return osa;
    }

    /**
     * Sets the value of the osa property.
     * 
     * @param value
     *     allowed object is
     *     {@link MurdType }
     *     
     */
    public void setOsa(MurdType value) {
        this.osa = value;
    }

}
