//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lisadokumendid_paring complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lisadokumendid_paring"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ettevotja_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kande_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="menetlused_id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="ekande_liik" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="esitaja_nimi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="esitaja_kood" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="markus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="lisadokumendid" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}lisadokument_type" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lisadokumendid_paring", propOrder = {
    "ettevotjaId",
    "kandeId",
    "menetlusedId",
    "ekandeLiik",
    "esitajaNimi",
    "esitajaKood",
    "markus",
    "lisadokumendid"
})
public class LisadokumendidParing {

    @XmlElement(name = "ettevotja_id", required = true)
    protected java.lang.String ettevotjaId;
    @XmlElement(name = "kande_id", required = true)
    protected java.lang.String kandeId;
    @XmlElement(name = "menetlused_id")
    protected int menetlusedId;
    @XmlElement(name = "ekande_liik")
    protected int ekandeLiik;
    @XmlElement(name = "esitaja_nimi", required = true)
    protected java.lang.String esitajaNimi;
    @XmlElement(name = "esitaja_kood", required = true)
    protected java.lang.String esitajaKood;
    protected java.lang.String markus;
    @XmlElement(required = true)
    protected List<LisadokumentType> lisadokumendid;

    /**
     * Gets the value of the ettevotjaId property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getEttevotjaId() {
        return ettevotjaId;
    }

    /**
     * Sets the value of the ettevotjaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setEttevotjaId(java.lang.String value) {
        this.ettevotjaId = value;
    }

    /**
     * Gets the value of the kandeId property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getKandeId() {
        return kandeId;
    }

    /**
     * Sets the value of the kandeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setKandeId(java.lang.String value) {
        this.kandeId = value;
    }

    /**
     * Gets the value of the menetlusedId property.
     * 
     */
    public int getMenetlusedId() {
        return menetlusedId;
    }

    /**
     * Sets the value of the menetlusedId property.
     * 
     */
    public void setMenetlusedId(int value) {
        this.menetlusedId = value;
    }

    /**
     * Gets the value of the ekandeLiik property.
     * 
     */
    public int getEkandeLiik() {
        return ekandeLiik;
    }

    /**
     * Sets the value of the ekandeLiik property.
     * 
     */
    public void setEkandeLiik(int value) {
        this.ekandeLiik = value;
    }

    /**
     * Gets the value of the esitajaNimi property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getEsitajaNimi() {
        return esitajaNimi;
    }

    /**
     * Sets the value of the esitajaNimi property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setEsitajaNimi(java.lang.String value) {
        this.esitajaNimi = value;
    }

    /**
     * Gets the value of the esitajaKood property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getEsitajaKood() {
        return esitajaKood;
    }

    /**
     * Sets the value of the esitajaKood property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setEsitajaKood(java.lang.String value) {
        this.esitajaKood = value;
    }

    /**
     * Gets the value of the markus property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getMarkus() {
        return markus;
    }

    /**
     * Sets the value of the markus property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setMarkus(java.lang.String value) {
        this.markus = value;
    }

    /**
     * Gets the value of the lisadokumendid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lisadokumendid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLisadokumendid().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LisadokumentType }
     * 
     * 
     */
    public List<LisadokumentType> getLisadokumendid() {
        if (lisadokumendid == null) {
            lisadokumendid = new ArrayList<LisadokumentType>();
        }
        return this.lisadokumendid;
    }

}
