//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mtaasutajad_vastus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mtaasutajad_vastus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="asutajad" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}mtaasutajad_asutajad"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mtaasutajad_vastus", propOrder = {
    "asutajad"
})
public class MtaasutajadVastus {

    @XmlElement(required = true)
    protected MtaasutajadAsutajad asutajad;

    /**
     * Gets the value of the asutajad property.
     * 
     * @return
     *     possible object is
     *     {@link MtaasutajadAsutajad }
     *     
     */
    public MtaasutajadAsutajad getAsutajad() {
        return asutajad;
    }

    /**
     * Sets the value of the asutajad property.
     * 
     * @param value
     *     allowed object is
     *     {@link MtaasutajadAsutajad }
     *     
     */
    public void setAsutajad(MtaasutajadAsutajad value) {
        this.asutajad = value;
    }

}
