//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Lihtmurd
 * 
 * <p>Java class for murdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="murdType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="lugeja" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="nimetaja" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "murdType", propOrder = {
    "lugeja",
    "nimetaja"
})
public class MurdType {

    protected int lugeja;
    protected int nimetaja;

    /**
     * Gets the value of the lugeja property.
     * 
     */
    public int getLugeja() {
        return lugeja;
    }

    /**
     * Sets the value of the lugeja property.
     * 
     */
    public void setLugeja(int value) {
        this.lugeja = value;
    }

    /**
     * Gets the value of the nimetaja property.
     * 
     */
    public int getNimetaja() {
        return nimetaja;
    }

    /**
     * Sets the value of the nimetaja property.
     * 
     */
    public void setNimetaja(int value) {
        this.nimetaja = value;
    }

}
