//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for omandType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="omandType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="suurus" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="omandiliik" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}x_omandiliik"/&gt;
 *         &lt;element name="roll" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}x_isikuroll"/&gt;
 *         &lt;element name="omanikud" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}kapitaliOmanikTypeArray"/&gt;
 *         &lt;element name="liikmesus" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}hy_liikmesusType" minOccurs="0"/&gt;
 *         &lt;element name="kontakt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "omandType", propOrder = {
    "suurus",
    "omandiliik",
    "roll",
    "omanikud",
    "liikmesus",
    "kontakt"
})
public class OmandType {

    @XmlElement(required = true)
    protected BigDecimal suurus;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected XOmandiliik omandiliik;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected XIsikuroll roll;
    @XmlElement(required = true)
    protected KapitaliOmanikTypeArray omanikud;
    protected HyLiikmesusType liikmesus;
    protected java.lang.String kontakt;

    /**
     * Gets the value of the suurus property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSuurus() {
        return suurus;
    }

    /**
     * Sets the value of the suurus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSuurus(BigDecimal value) {
        this.suurus = value;
    }

    /**
     * Gets the value of the omandiliik property.
     * 
     * @return
     *     possible object is
     *     {@link XOmandiliik }
     *     
     */
    public XOmandiliik getOmandiliik() {
        return omandiliik;
    }

    /**
     * Sets the value of the omandiliik property.
     * 
     * @param value
     *     allowed object is
     *     {@link XOmandiliik }
     *     
     */
    public void setOmandiliik(XOmandiliik value) {
        this.omandiliik = value;
    }

    /**
     * Gets the value of the roll property.
     * 
     * @return
     *     possible object is
     *     {@link XIsikuroll }
     *     
     */
    public XIsikuroll getRoll() {
        return roll;
    }

    /**
     * Sets the value of the roll property.
     * 
     * @param value
     *     allowed object is
     *     {@link XIsikuroll }
     *     
     */
    public void setRoll(XIsikuroll value) {
        this.roll = value;
    }

    /**
     * Gets the value of the omanikud property.
     * 
     * @return
     *     possible object is
     *     {@link KapitaliOmanikTypeArray }
     *     
     */
    public KapitaliOmanikTypeArray getOmanikud() {
        return omanikud;
    }

    /**
     * Sets the value of the omanikud property.
     * 
     * @param value
     *     allowed object is
     *     {@link KapitaliOmanikTypeArray }
     *     
     */
    public void setOmanikud(KapitaliOmanikTypeArray value) {
        this.omanikud = value;
    }

    /**
     * Gets the value of the liikmesus property.
     * 
     * @return
     *     possible object is
     *     {@link HyLiikmesusType }
     *     
     */
    public HyLiikmesusType getLiikmesus() {
        return liikmesus;
    }

    /**
     * Sets the value of the liikmesus property.
     * 
     * @param value
     *     allowed object is
     *     {@link HyLiikmesusType }
     *     
     */
    public void setLiikmesus(HyLiikmesusType value) {
        this.liikmesus = value;
    }

    /**
     * Gets the value of the kontakt property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getKontakt() {
        return kontakt;
    }

    /**
     * Sets the value of the kontakt property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setKontakt(java.lang.String value) {
        this.kontakt = value;
    }

}
