//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for osapantType_v3 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="osapantType_v3"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pandipidajad" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}kapitaliOmanikType_v3" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="liik" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="jarjekoht" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="omandiliik" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="algus" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="lopp" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "osapantType_v3", propOrder = {
    "pandipidajad",
    "liik",
    "jarjekoht",
    "omandiliik",
    "algus",
    "lopp"
})
public class OsapantTypeV3 {

    @XmlElement(nillable = true)
    protected List<KapitaliOmanikTypeV3> pandipidajad;
    @XmlElement(required = true)
    protected java.lang.String liik;
    protected short jarjekoht;
    @XmlElement(required = true)
    protected java.lang.String omandiliik;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar algus;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lopp;

    /**
     * Gets the value of the pandipidajad property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pandipidajad property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPandipidajad().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KapitaliOmanikTypeV3 }
     * 
     * 
     */
    public List<KapitaliOmanikTypeV3> getPandipidajad() {
        if (pandipidajad == null) {
            pandipidajad = new ArrayList<KapitaliOmanikTypeV3>();
        }
        return this.pandipidajad;
    }

    /**
     * Gets the value of the liik property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getLiik() {
        return liik;
    }

    /**
     * Sets the value of the liik property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setLiik(java.lang.String value) {
        this.liik = value;
    }

    /**
     * Gets the value of the jarjekoht property.
     * 
     */
    public short getJarjekoht() {
        return jarjekoht;
    }

    /**
     * Sets the value of the jarjekoht property.
     * 
     */
    public void setJarjekoht(short value) {
        this.jarjekoht = value;
    }

    /**
     * Gets the value of the omandiliik property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getOmandiliik() {
        return omandiliik;
    }

    /**
     * Sets the value of the omandiliik property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setOmandiliik(java.lang.String value) {
        this.omandiliik = value;
    }

    /**
     * Gets the value of the algus property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAlgus() {
        return algus;
    }

    /**
     * Sets the value of the algus property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAlgus(XMLGregorianCalendar value) {
        this.algus = value;
    }

    /**
     * Gets the value of the lopp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLopp() {
        return lopp;
    }

    /**
     * Sets the value of the lopp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLopp(XMLGregorianCalendar value) {
        this.lopp = value;
    }

}
