//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://producers.arireg.xtee.riik.ee/producer/arireg")
package ee.rik.kris5.xroad.model.soap;
