//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import java.math.BigInteger;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for paringliht_v3_vastus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paringliht_v3_vastus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ettevotjad" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}paringliht_v3_ettevotted"/&gt;
 *         &lt;element name="leitud_ettevotjate_arv" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paringliht_v3_vastus", propOrder = {
    "ettevotjad",
    "leitudEttevotjateArv"
})
public class ParinglihtV3Vastus {

    @XmlElement(required = true)
    protected ParinglihtV3Ettevotted ettevotjad;
    @XmlElement(name = "leitud_ettevotjate_arv", required = true)
    protected BigInteger leitudEttevotjateArv;

    /**
     * Gets the value of the ettevotjad property.
     * 
     * @return
     *     possible object is
     *     {@link ParinglihtV3Ettevotted }
     *     
     */
    public ParinglihtV3Ettevotted getEttevotjad() {
        return ettevotjad;
    }

    /**
     * Sets the value of the ettevotjad property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParinglihtV3Ettevotted }
     *     
     */
    public void setEttevotjad(ParinglihtV3Ettevotted value) {
        this.ettevotjad = value;
    }

    /**
     * Gets the value of the leitudEttevotjateArv property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLeitudEttevotjateArv() {
        return leitudEttevotjateArv;
    }

    /**
     * Sets the value of the leitudEttevotjateArv property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLeitudEttevotjateArv(BigInteger value) {
        this.leitudEttevotjateArv = value;
    }

}
