//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for paringliht_ettevote complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paringliht_ettevote"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="evnimi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kehtetud_nimed" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}paringliht_kehtetudnimed"/&gt;
 *         &lt;element name="ariregistri_kood" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="staatus" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}x_evstaatus"/&gt;
 *         &lt;element name="registrist_kustutamise_aeg" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="piirkond" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}x_piirkond"/&gt;
 *         &lt;element name="evkapitalid" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}paringliht_evkapital"/&gt;
 *         &lt;element name="evaadressid" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}paringliht_evaadress"/&gt;
 *         &lt;element name="esmakande_aeg" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paringliht_ettevote", propOrder = {
    "evnimi",
    "kehtetudNimed",
    "ariregistriKood",
    "staatus",
    "registristKustutamiseAeg",
    "piirkond",
    "evkapitalid",
    "evaadressid",
    "esmakandeAeg"
})
public class ParinglihtEttevote {

    @XmlElement(required = true)
    protected java.lang.String evnimi;
    @XmlElement(name = "kehtetud_nimed", required = true, nillable = true)
    protected ParinglihtKehtetudnimed kehtetudNimed;
    @XmlElement(name = "ariregistri_kood", required = true)
    protected java.lang.String ariregistriKood;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected XEvstaatus staatus;
    @XmlElement(name = "registrist_kustutamise_aeg", required = true, nillable = true)
    protected java.lang.String registristKustutamiseAeg;
    @XmlElement(required = true)
    protected java.lang.String piirkond;
    @XmlElement(required = true, nillable = true)
    protected ParinglihtEvkapital evkapitalid;
    @XmlElement(required = true, nillable = true)
    protected ParinglihtEvaadress evaadressid;
    @XmlElement(name = "esmakande_aeg", required = true, nillable = true)
    protected java.lang.String esmakandeAeg;

    /**
     * Gets the value of the evnimi property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getEvnimi() {
        return evnimi;
    }

    /**
     * Sets the value of the evnimi property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setEvnimi(java.lang.String value) {
        this.evnimi = value;
    }

    /**
     * Gets the value of the kehtetudNimed property.
     * 
     * @return
     *     possible object is
     *     {@link ParinglihtKehtetudnimed }
     *     
     */
    public ParinglihtKehtetudnimed getKehtetudNimed() {
        return kehtetudNimed;
    }

    /**
     * Sets the value of the kehtetudNimed property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParinglihtKehtetudnimed }
     *     
     */
    public void setKehtetudNimed(ParinglihtKehtetudnimed value) {
        this.kehtetudNimed = value;
    }

    /**
     * Gets the value of the ariregistriKood property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getAriregistriKood() {
        return ariregistriKood;
    }

    /**
     * Sets the value of the ariregistriKood property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setAriregistriKood(java.lang.String value) {
        this.ariregistriKood = value;
    }

    /**
     * Gets the value of the staatus property.
     * 
     * @return
     *     possible object is
     *     {@link XEvstaatus }
     *     
     */
    public XEvstaatus getStaatus() {
        return staatus;
    }

    /**
     * Sets the value of the staatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link XEvstaatus }
     *     
     */
    public void setStaatus(XEvstaatus value) {
        this.staatus = value;
    }

    /**
     * Gets the value of the registristKustutamiseAeg property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getRegistristKustutamiseAeg() {
        return registristKustutamiseAeg;
    }

    /**
     * Sets the value of the registristKustutamiseAeg property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setRegistristKustutamiseAeg(java.lang.String value) {
        this.registristKustutamiseAeg = value;
    }

    /**
     * Gets the value of the piirkond property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getPiirkond() {
        return piirkond;
    }

    /**
     * Sets the value of the piirkond property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setPiirkond(java.lang.String value) {
        this.piirkond = value;
    }

    /**
     * Gets the value of the evkapitalid property.
     * 
     * @return
     *     possible object is
     *     {@link ParinglihtEvkapital }
     *     
     */
    public ParinglihtEvkapital getEvkapitalid() {
        return evkapitalid;
    }

    /**
     * Sets the value of the evkapitalid property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParinglihtEvkapital }
     *     
     */
    public void setEvkapitalid(ParinglihtEvkapital value) {
        this.evkapitalid = value;
    }

    /**
     * Gets the value of the evaadressid property.
     * 
     * @return
     *     possible object is
     *     {@link ParinglihtEvaadress }
     *     
     */
    public ParinglihtEvaadress getEvaadressid() {
        return evaadressid;
    }

    /**
     * Sets the value of the evaadressid property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParinglihtEvaadress }
     *     
     */
    public void setEvaadressid(ParinglihtEvaadress value) {
        this.evaadressid = value;
    }

    /**
     * Gets the value of the esmakandeAeg property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getEsmakandeAeg() {
        return esmakandeAeg;
    }

    /**
     * Sets the value of the esmakandeAeg property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setEsmakandeAeg(java.lang.String value) {
        this.esmakandeAeg = value;
    }

}
