//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for sooritakanne_ametitoiming_v4 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sooritakanne_ametitoiming_v4"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tehingu_kuupaev" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="ametitoimingu_nr" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="notari_nimi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="notari_isikukood" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sooritakanne_ametitoiming_v4", propOrder = {
    "tehinguKuupaev",
    "ametitoiminguNr",
    "notariNimi",
    "notariIsikukood"
})
public class SooritakanneAmetitoimingV4 {

    @XmlElement(name = "tehingu_kuupaev", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar tehinguKuupaev;
    @XmlElement(name = "ametitoimingu_nr")
    protected java.lang.Integer ametitoiminguNr;
    @XmlElement(name = "notari_nimi", required = true)
    protected java.lang.String notariNimi;
    @XmlElement(name = "notari_isikukood", required = true)
    protected java.lang.String notariIsikukood;

    /**
     * Gets the value of the tehinguKuupaev property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTehinguKuupaev() {
        return tehinguKuupaev;
    }

    /**
     * Sets the value of the tehinguKuupaev property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTehinguKuupaev(XMLGregorianCalendar value) {
        this.tehinguKuupaev = value;
    }

    /**
     * Gets the value of the ametitoiminguNr property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Integer }
     *     
     */
    public java.lang.Integer getAmetitoiminguNr() {
        return ametitoiminguNr;
    }

    /**
     * Sets the value of the ametitoiminguNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Integer }
     *     
     */
    public void setAmetitoiminguNr(java.lang.Integer value) {
        this.ametitoiminguNr = value;
    }

    /**
     * Gets the value of the notariNimi property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getNotariNimi() {
        return notariNimi;
    }

    /**
     * Sets the value of the notariNimi property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setNotariNimi(java.lang.String value) {
        this.notariNimi = value;
    }

    /**
     * Gets the value of the notariIsikukood property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getNotariIsikukood() {
        return notariIsikukood;
    }

    /**
     * Sets the value of the notariIsikukood property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setNotariIsikukood(java.lang.String value) {
        this.notariIsikukood = value;
    }

}
