//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sooritakanne_vmemaettevote_v3 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sooritakanne_vmemaettevote_v3"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="arinimi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="arinimi_seesytlevas" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="oiguslik_vorm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="oigusliku_vormi_markus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="registrikood" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="asukoht" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}aadressType" minOccurs="0"/&gt;
 *         &lt;element name="seaduste_alus_riik" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tegutsemise_maa_markus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="maj_aru_markus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="markused" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sooritakanne_vmemaettevote_v3", propOrder = {
    "arinimi",
    "arinimiSeesytlevas",
    "oiguslikVorm",
    "oiguslikuVormiMarkus",
    "registrikood",
    "asukoht",
    "seadusteAlusRiik",
    "tegutsemiseMaaMarkus",
    "majAruMarkus",
    "markused"
})
public class SooritakanneVmemaettevoteV3 {

    protected java.lang.String arinimi;
    @XmlElement(name = "arinimi_seesytlevas")
    protected java.lang.String arinimiSeesytlevas;
    @XmlElement(name = "oiguslik_vorm")
    protected java.lang.String oiguslikVorm;
    @XmlElement(name = "oigusliku_vormi_markus")
    protected java.lang.String oiguslikuVormiMarkus;
    protected java.lang.String registrikood;
    protected AadressType asukoht;
    @XmlElement(name = "seaduste_alus_riik")
    protected java.lang.String seadusteAlusRiik;
    @XmlElement(name = "tegutsemise_maa_markus")
    protected java.lang.String tegutsemiseMaaMarkus;
    @XmlElement(name = "maj_aru_markus")
    protected java.lang.String majAruMarkus;
    @XmlElement(nillable = true)
    protected List<java.lang.String> markused;

    /**
     * Gets the value of the arinimi property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getArinimi() {
        return arinimi;
    }

    /**
     * Sets the value of the arinimi property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setArinimi(java.lang.String value) {
        this.arinimi = value;
    }

    /**
     * Gets the value of the arinimiSeesytlevas property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getArinimiSeesytlevas() {
        return arinimiSeesytlevas;
    }

    /**
     * Sets the value of the arinimiSeesytlevas property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setArinimiSeesytlevas(java.lang.String value) {
        this.arinimiSeesytlevas = value;
    }

    /**
     * Gets the value of the oiguslikVorm property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getOiguslikVorm() {
        return oiguslikVorm;
    }

    /**
     * Sets the value of the oiguslikVorm property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setOiguslikVorm(java.lang.String value) {
        this.oiguslikVorm = value;
    }

    /**
     * Gets the value of the oiguslikuVormiMarkus property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getOiguslikuVormiMarkus() {
        return oiguslikuVormiMarkus;
    }

    /**
     * Sets the value of the oiguslikuVormiMarkus property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setOiguslikuVormiMarkus(java.lang.String value) {
        this.oiguslikuVormiMarkus = value;
    }

    /**
     * Gets the value of the registrikood property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getRegistrikood() {
        return registrikood;
    }

    /**
     * Sets the value of the registrikood property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setRegistrikood(java.lang.String value) {
        this.registrikood = value;
    }

    /**
     * Gets the value of the asukoht property.
     * 
     * @return
     *     possible object is
     *     {@link AadressType }
     *     
     */
    public AadressType getAsukoht() {
        return asukoht;
    }

    /**
     * Sets the value of the asukoht property.
     * 
     * @param value
     *     allowed object is
     *     {@link AadressType }
     *     
     */
    public void setAsukoht(AadressType value) {
        this.asukoht = value;
    }

    /**
     * Gets the value of the seadusteAlusRiik property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getSeadusteAlusRiik() {
        return seadusteAlusRiik;
    }

    /**
     * Sets the value of the seadusteAlusRiik property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setSeadusteAlusRiik(java.lang.String value) {
        this.seadusteAlusRiik = value;
    }

    /**
     * Gets the value of the tegutsemiseMaaMarkus property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getTegutsemiseMaaMarkus() {
        return tegutsemiseMaaMarkus;
    }

    /**
     * Sets the value of the tegutsemiseMaaMarkus property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setTegutsemiseMaaMarkus(java.lang.String value) {
        this.tegutsemiseMaaMarkus = value;
    }

    /**
     * Gets the value of the majAruMarkus property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getMajAruMarkus() {
        return majAruMarkus;
    }

    /**
     * Sets the value of the majAruMarkus property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setMajAruMarkus(java.lang.String value) {
        this.majAruMarkus = value;
    }

    /**
     * Gets the value of the markused property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the markused property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarkused().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.lang.String }
     * 
     * 
     */
    public List<java.lang.String> getMarkused() {
        if (markused == null) {
            markused = new ArrayList<java.lang.String>();
        }
        return this.markused;
    }

}
