//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for sooritakanne_kandesisu_v3 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sooritakanne_kandesisu_v3"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="registrikood" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="algne_arinimi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="uus_arinimi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="oiguslik_vorm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="oigusliku_vormi_alaliik" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="asukoht" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}aadressType" minOccurs="0"/&gt;
 *         &lt;element name="pohitegevusala" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}tegevusalaType" minOccurs="0"/&gt;
 *         &lt;element name="lisategevusala" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}tegevusalaType" minOccurs="0"/&gt;
 *         &lt;element name="eesmargid" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="majandusaasta" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}sooritakanne_majaasta" minOccurs="0"/&gt;
 *         &lt;element name="kapital" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}sooritakanne_kapital" minOccurs="0"/&gt;
 *         &lt;element name="asutatud_sissemakset_tegemata" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="kapitali_jagunemised" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}kapitaliJagunemineType_v3" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="esindusoigused" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}esindusoigusType_v3" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="pohikiri" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}sooritakanne_pohikiri" minOccurs="0"/&gt;
 *         &lt;element name="sidevahendid" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}sidevahendType_v3" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="seotud_isikud" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}seotud_isik_v3" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="markused" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="tegutsemise_algus" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="tegutsemise_tahtaeg" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="asutamise_aeg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="viide_eelkaijale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="kinnisasjad" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}kinnisasiType_v3" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="valismaa_emaettevote" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}sooritakanne_vmemaettevote_v3" minOccurs="0"/&gt;
 *         &lt;element name="fie_seisundid" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}sooritakanne_fieseisund" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="maks_reg_kpv" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sooritakanne_kandesisu_v3", propOrder = {
    "registrikood",
    "algneArinimi",
    "uusArinimi",
    "oiguslikVorm",
    "oiguslikuVormiAlaliik",
    "asukoht",
    "pohitegevusala",
    "lisategevusala",
    "eesmargid",
    "majandusaasta",
    "kapital",
    "asutatudSissemaksetTegemata",
    "kapitaliJagunemised",
    "esindusoigused",
    "pohikiri",
    "sidevahendid",
    "seotudIsikud",
    "markused",
    "tegutsemiseAlgus",
    "tegutsemiseTahtaeg",
    "asutamiseAeg",
    "viideEelkaijale",
    "kinnisasjad",
    "valismaaEmaettevote",
    "fieSeisundid",
    "maksRegKpv"
})
public class SooritakanneKandesisuV3 {

    protected java.lang.Integer registrikood;
    @XmlElement(name = "algne_arinimi")
    protected java.lang.String algneArinimi;
    @XmlElement(name = "uus_arinimi")
    protected java.lang.String uusArinimi;
    @XmlElement(name = "oiguslik_vorm")
    protected java.lang.String oiguslikVorm;
    @XmlElementRef(name = "oigusliku_vormi_alaliik", type = JAXBElement.class, required = false)
    protected JAXBElement<java.lang.String> oiguslikuVormiAlaliik;
    protected AadressType asukoht;
    protected TegevusalaType pohitegevusala;
    protected TegevusalaType lisategevusala;
    @XmlElement(nillable = true)
    protected List<java.lang.String> eesmargid;
    protected SooritakanneMajaasta majandusaasta;
    protected SooritakanneKapital kapital;
    @XmlElementRef(name = "asutatud_sissemakset_tegemata", type = JAXBElement.class, required = false)
    protected JAXBElement<java.lang.Boolean> asutatudSissemaksetTegemata;
    @XmlElement(name = "kapitali_jagunemised", nillable = true)
    protected List<KapitaliJagunemineTypeV3> kapitaliJagunemised;
    @XmlElement(nillable = true)
    protected List<EsindusoigusTypeV3> esindusoigused;
    protected SooritakannePohikiri pohikiri;
    @XmlElement(nillable = true)
    protected List<SidevahendTypeV3> sidevahendid;
    @XmlElement(name = "seotud_isikud", nillable = true)
    protected List<SeotudIsikV3> seotudIsikud;
    @XmlElement(nillable = true)
    protected List<java.lang.String> markused;
    @XmlElement(name = "tegutsemise_algus")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar tegutsemiseAlgus;
    @XmlElement(name = "tegutsemise_tahtaeg")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar tegutsemiseTahtaeg;
    @XmlElement(name = "asutamise_aeg")
    protected java.lang.String asutamiseAeg;
    @XmlElement(name = "viide_eelkaijale")
    protected java.lang.String viideEelkaijale;
    @XmlElement(nillable = true)
    protected List<KinnisasiTypeV3> kinnisasjad;
    @XmlElement(name = "valismaa_emaettevote")
    protected SooritakanneVmemaettevoteV3 valismaaEmaettevote;
    @XmlElement(name = "fie_seisundid", nillable = true)
    protected List<SooritakanneFieseisund> fieSeisundid;
    @XmlElement(name = "maks_reg_kpv")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar maksRegKpv;

    /**
     * Gets the value of the registrikood property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Integer }
     *     
     */
    public java.lang.Integer getRegistrikood() {
        return registrikood;
    }

    /**
     * Sets the value of the registrikood property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Integer }
     *     
     */
    public void setRegistrikood(java.lang.Integer value) {
        this.registrikood = value;
    }

    /**
     * Gets the value of the algneArinimi property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getAlgneArinimi() {
        return algneArinimi;
    }

    /**
     * Sets the value of the algneArinimi property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setAlgneArinimi(java.lang.String value) {
        this.algneArinimi = value;
    }

    /**
     * Gets the value of the uusArinimi property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getUusArinimi() {
        return uusArinimi;
    }

    /**
     * Sets the value of the uusArinimi property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setUusArinimi(java.lang.String value) {
        this.uusArinimi = value;
    }

    /**
     * Gets the value of the oiguslikVorm property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getOiguslikVorm() {
        return oiguslikVorm;
    }

    /**
     * Sets the value of the oiguslikVorm property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setOiguslikVorm(java.lang.String value) {
        this.oiguslikVorm = value;
    }

    /**
     * Gets the value of the oiguslikuVormiAlaliik property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}
     *     
     */
    public JAXBElement<java.lang.String> getOiguslikuVormiAlaliik() {
        return oiguslikuVormiAlaliik;
    }

    /**
     * Sets the value of the oiguslikuVormiAlaliik property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}
     *     
     */
    public void setOiguslikuVormiAlaliik(JAXBElement<java.lang.String> value) {
        this.oiguslikuVormiAlaliik = value;
    }

    /**
     * Gets the value of the asukoht property.
     * 
     * @return
     *     possible object is
     *     {@link AadressType }
     *     
     */
    public AadressType getAsukoht() {
        return asukoht;
    }

    /**
     * Sets the value of the asukoht property.
     * 
     * @param value
     *     allowed object is
     *     {@link AadressType }
     *     
     */
    public void setAsukoht(AadressType value) {
        this.asukoht = value;
    }

    /**
     * Gets the value of the pohitegevusala property.
     * 
     * @return
     *     possible object is
     *     {@link TegevusalaType }
     *     
     */
    public TegevusalaType getPohitegevusala() {
        return pohitegevusala;
    }

    /**
     * Sets the value of the pohitegevusala property.
     * 
     * @param value
     *     allowed object is
     *     {@link TegevusalaType }
     *     
     */
    public void setPohitegevusala(TegevusalaType value) {
        this.pohitegevusala = value;
    }

    /**
     * Gets the value of the lisategevusala property.
     * 
     * @return
     *     possible object is
     *     {@link TegevusalaType }
     *     
     */
    public TegevusalaType getLisategevusala() {
        return lisategevusala;
    }

    /**
     * Sets the value of the lisategevusala property.
     * 
     * @param value
     *     allowed object is
     *     {@link TegevusalaType }
     *     
     */
    public void setLisategevusala(TegevusalaType value) {
        this.lisategevusala = value;
    }

    /**
     * Gets the value of the eesmargid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eesmargid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEesmargid().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.lang.String }
     * 
     * 
     */
    public List<java.lang.String> getEesmargid() {
        if (eesmargid == null) {
            eesmargid = new ArrayList<java.lang.String>();
        }
        return this.eesmargid;
    }

    /**
     * Gets the value of the majandusaasta property.
     * 
     * @return
     *     possible object is
     *     {@link SooritakanneMajaasta }
     *     
     */
    public SooritakanneMajaasta getMajandusaasta() {
        return majandusaasta;
    }

    /**
     * Sets the value of the majandusaasta property.
     * 
     * @param value
     *     allowed object is
     *     {@link SooritakanneMajaasta }
     *     
     */
    public void setMajandusaasta(SooritakanneMajaasta value) {
        this.majandusaasta = value;
    }

    /**
     * Gets the value of the kapital property.
     * 
     * @return
     *     possible object is
     *     {@link SooritakanneKapital }
     *     
     */
    public SooritakanneKapital getKapital() {
        return kapital;
    }

    /**
     * Sets the value of the kapital property.
     * 
     * @param value
     *     allowed object is
     *     {@link SooritakanneKapital }
     *     
     */
    public void setKapital(SooritakanneKapital value) {
        this.kapital = value;
    }

    /**
     * Gets the value of the asutatudSissemaksetTegemata property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link java.lang.Boolean }{@code >}
     *     
     */
    public JAXBElement<java.lang.Boolean> getAsutatudSissemaksetTegemata() {
        return asutatudSissemaksetTegemata;
    }

    /**
     * Sets the value of the asutatudSissemaksetTegemata property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link java.lang.Boolean }{@code >}
     *     
     */
    public void setAsutatudSissemaksetTegemata(JAXBElement<java.lang.Boolean> value) {
        this.asutatudSissemaksetTegemata = value;
    }

    /**
     * Gets the value of the kapitaliJagunemised property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kapitaliJagunemised property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKapitaliJagunemised().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KapitaliJagunemineTypeV3 }
     * 
     * 
     */
    public List<KapitaliJagunemineTypeV3> getKapitaliJagunemised() {
        if (kapitaliJagunemised == null) {
            kapitaliJagunemised = new ArrayList<KapitaliJagunemineTypeV3>();
        }
        return this.kapitaliJagunemised;
    }

    /**
     * Gets the value of the esindusoigused property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the esindusoigused property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEsindusoigused().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EsindusoigusTypeV3 }
     * 
     * 
     */
    public List<EsindusoigusTypeV3> getEsindusoigused() {
        if (esindusoigused == null) {
            esindusoigused = new ArrayList<EsindusoigusTypeV3>();
        }
        return this.esindusoigused;
    }

    /**
     * Gets the value of the pohikiri property.
     * 
     * @return
     *     possible object is
     *     {@link SooritakannePohikiri }
     *     
     */
    public SooritakannePohikiri getPohikiri() {
        return pohikiri;
    }

    /**
     * Sets the value of the pohikiri property.
     * 
     * @param value
     *     allowed object is
     *     {@link SooritakannePohikiri }
     *     
     */
    public void setPohikiri(SooritakannePohikiri value) {
        this.pohikiri = value;
    }

    /**
     * Gets the value of the sidevahendid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sidevahendid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSidevahendid().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SidevahendTypeV3 }
     * 
     * 
     */
    public List<SidevahendTypeV3> getSidevahendid() {
        if (sidevahendid == null) {
            sidevahendid = new ArrayList<SidevahendTypeV3>();
        }
        return this.sidevahendid;
    }

    /**
     * Gets the value of the seotudIsikud property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the seotudIsikud property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSeotudIsikud().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SeotudIsikV3 }
     * 
     * 
     */
    public List<SeotudIsikV3> getSeotudIsikud() {
        if (seotudIsikud == null) {
            seotudIsikud = new ArrayList<SeotudIsikV3>();
        }
        return this.seotudIsikud;
    }

    /**
     * Gets the value of the markused property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the markused property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarkused().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.lang.String }
     * 
     * 
     */
    public List<java.lang.String> getMarkused() {
        if (markused == null) {
            markused = new ArrayList<java.lang.String>();
        }
        return this.markused;
    }

    /**
     * Gets the value of the tegutsemiseAlgus property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTegutsemiseAlgus() {
        return tegutsemiseAlgus;
    }

    /**
     * Sets the value of the tegutsemiseAlgus property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTegutsemiseAlgus(XMLGregorianCalendar value) {
        this.tegutsemiseAlgus = value;
    }

    /**
     * Gets the value of the tegutsemiseTahtaeg property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTegutsemiseTahtaeg() {
        return tegutsemiseTahtaeg;
    }

    /**
     * Sets the value of the tegutsemiseTahtaeg property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTegutsemiseTahtaeg(XMLGregorianCalendar value) {
        this.tegutsemiseTahtaeg = value;
    }

    /**
     * Gets the value of the asutamiseAeg property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getAsutamiseAeg() {
        return asutamiseAeg;
    }

    /**
     * Sets the value of the asutamiseAeg property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setAsutamiseAeg(java.lang.String value) {
        this.asutamiseAeg = value;
    }

    /**
     * Gets the value of the viideEelkaijale property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getViideEelkaijale() {
        return viideEelkaijale;
    }

    /**
     * Sets the value of the viideEelkaijale property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setViideEelkaijale(java.lang.String value) {
        this.viideEelkaijale = value;
    }

    /**
     * Gets the value of the kinnisasjad property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kinnisasjad property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKinnisasjad().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KinnisasiTypeV3 }
     * 
     * 
     */
    public List<KinnisasiTypeV3> getKinnisasjad() {
        if (kinnisasjad == null) {
            kinnisasjad = new ArrayList<KinnisasiTypeV3>();
        }
        return this.kinnisasjad;
    }

    /**
     * Gets the value of the valismaaEmaettevote property.
     * 
     * @return
     *     possible object is
     *     {@link SooritakanneVmemaettevoteV3 }
     *     
     */
    public SooritakanneVmemaettevoteV3 getValismaaEmaettevote() {
        return valismaaEmaettevote;
    }

    /**
     * Sets the value of the valismaaEmaettevote property.
     * 
     * @param value
     *     allowed object is
     *     {@link SooritakanneVmemaettevoteV3 }
     *     
     */
    public void setValismaaEmaettevote(SooritakanneVmemaettevoteV3 value) {
        this.valismaaEmaettevote = value;
    }

    /**
     * Gets the value of the fieSeisundid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieSeisundid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieSeisundid().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SooritakanneFieseisund }
     * 
     * 
     */
    public List<SooritakanneFieseisund> getFieSeisundid() {
        if (fieSeisundid == null) {
            fieSeisundid = new ArrayList<SooritakanneFieseisund>();
        }
        return this.fieSeisundid;
    }

    /**
     * Gets the value of the maksRegKpv property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMaksRegKpv() {
        return maksRegKpv;
    }

    /**
     * Sets the value of the maksRegKpv property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMaksRegKpv(XMLGregorianCalendar value) {
        this.maksRegKpv = value;
    }

}
