//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for xbrl_aruande_naitajad_paring complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xbrl_aruande_naitajad_paring"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="xbrl_aruande_id" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="paev_nr" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="maj_algus" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="maj_lopp" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="ehak" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="aadress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="postiind" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pteg_emtak" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pteg_emtak_versioon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="esitatud" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="ark" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="tootajate_arv" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="kaive" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="kasum" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="bilansimaht" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="valuuta" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="esitamise_viis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="auditeerimiskohustus" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="auditeeritus" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="bilansi_sisud" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}xbrl_aruande_bilansi_sisud"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xbrl_aruande_naitajad_paring", propOrder = {
    "xbrlAruandeId",
    "paevNr",
    "majAlgus",
    "majLopp",
    "ehak",
    "aadress",
    "postiind",
    "ptegEmtak",
    "ptegEmtakVersioon",
    "esitatud",
    "ark",
    "tootajateArv",
    "kaive",
    "kasum",
    "bilansimaht",
    "valuuta",
    "esitamiseViis",
    "auditeerimiskohustus",
    "auditeeritus",
    "bilansiSisud"
})
public class XbrlAruandeNaitajadParing {

    @XmlElement(name = "xbrl_aruande_id", required = true)
    protected BigInteger xbrlAruandeId;
    @XmlElement(name = "paev_nr", required = true)
    protected BigInteger paevNr;
    @XmlElement(name = "maj_algus", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar majAlgus;
    @XmlElement(name = "maj_lopp", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar majLopp;
    protected java.lang.String ehak;
    protected java.lang.String aadress;
    protected java.lang.String postiind;
    @XmlElement(name = "pteg_emtak")
    protected java.lang.String ptegEmtak;
    @XmlElement(name = "pteg_emtak_versioon")
    protected java.lang.String ptegEmtakVersioon;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar esitatud;
    @XmlElement(required = true)
    protected BigInteger ark;
    @XmlElement(name = "tootajate_arv")
    protected BigInteger tootajateArv;
    protected BigInteger kaive;
    protected BigInteger kasum;
    protected BigInteger bilansimaht;
    @XmlElement(required = true)
    protected java.lang.String valuuta;
    @XmlElement(name = "esitamise_viis")
    protected java.lang.String esitamiseViis;
    protected java.lang.Boolean auditeerimiskohustus;
    protected java.lang.Boolean auditeeritus;
    @XmlElement(name = "bilansi_sisud", required = true)
    protected XbrlAruandeBilansiSisud bilansiSisud;

    /**
     * Gets the value of the xbrlAruandeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getXbrlAruandeId() {
        return xbrlAruandeId;
    }

    /**
     * Sets the value of the xbrlAruandeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setXbrlAruandeId(BigInteger value) {
        this.xbrlAruandeId = value;
    }

    /**
     * Gets the value of the paevNr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPaevNr() {
        return paevNr;
    }

    /**
     * Sets the value of the paevNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPaevNr(BigInteger value) {
        this.paevNr = value;
    }

    /**
     * Gets the value of the majAlgus property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMajAlgus() {
        return majAlgus;
    }

    /**
     * Sets the value of the majAlgus property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMajAlgus(XMLGregorianCalendar value) {
        this.majAlgus = value;
    }

    /**
     * Gets the value of the majLopp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMajLopp() {
        return majLopp;
    }

    /**
     * Sets the value of the majLopp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMajLopp(XMLGregorianCalendar value) {
        this.majLopp = value;
    }

    /**
     * Gets the value of the ehak property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getEhak() {
        return ehak;
    }

    /**
     * Sets the value of the ehak property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setEhak(java.lang.String value) {
        this.ehak = value;
    }

    /**
     * Gets the value of the aadress property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getAadress() {
        return aadress;
    }

    /**
     * Sets the value of the aadress property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setAadress(java.lang.String value) {
        this.aadress = value;
    }

    /**
     * Gets the value of the postiind property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getPostiind() {
        return postiind;
    }

    /**
     * Sets the value of the postiind property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setPostiind(java.lang.String value) {
        this.postiind = value;
    }

    /**
     * Gets the value of the ptegEmtak property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getPtegEmtak() {
        return ptegEmtak;
    }

    /**
     * Sets the value of the ptegEmtak property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setPtegEmtak(java.lang.String value) {
        this.ptegEmtak = value;
    }

    /**
     * Gets the value of the ptegEmtakVersioon property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getPtegEmtakVersioon() {
        return ptegEmtakVersioon;
    }

    /**
     * Sets the value of the ptegEmtakVersioon property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setPtegEmtakVersioon(java.lang.String value) {
        this.ptegEmtakVersioon = value;
    }

    /**
     * Gets the value of the esitatud property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEsitatud() {
        return esitatud;
    }

    /**
     * Sets the value of the esitatud property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEsitatud(XMLGregorianCalendar value) {
        this.esitatud = value;
    }

    /**
     * Gets the value of the ark property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getArk() {
        return ark;
    }

    /**
     * Sets the value of the ark property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setArk(BigInteger value) {
        this.ark = value;
    }

    /**
     * Gets the value of the tootajateArv property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTootajateArv() {
        return tootajateArv;
    }

    /**
     * Sets the value of the tootajateArv property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTootajateArv(BigInteger value) {
        this.tootajateArv = value;
    }

    /**
     * Gets the value of the kaive property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getKaive() {
        return kaive;
    }

    /**
     * Sets the value of the kaive property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setKaive(BigInteger value) {
        this.kaive = value;
    }

    /**
     * Gets the value of the kasum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getKasum() {
        return kasum;
    }

    /**
     * Sets the value of the kasum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setKasum(BigInteger value) {
        this.kasum = value;
    }

    /**
     * Gets the value of the bilansimaht property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBilansimaht() {
        return bilansimaht;
    }

    /**
     * Sets the value of the bilansimaht property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBilansimaht(BigInteger value) {
        this.bilansimaht = value;
    }

    /**
     * Gets the value of the valuuta property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getValuuta() {
        return valuuta;
    }

    /**
     * Sets the value of the valuuta property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setValuuta(java.lang.String value) {
        this.valuuta = value;
    }

    /**
     * Gets the value of the esitamiseViis property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getEsitamiseViis() {
        return esitamiseViis;
    }

    /**
     * Sets the value of the esitamiseViis property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setEsitamiseViis(java.lang.String value) {
        this.esitamiseViis = value;
    }

    /**
     * Gets the value of the auditeerimiskohustus property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public java.lang.Boolean isAuditeerimiskohustus() {
        return auditeerimiskohustus;
    }

    /**
     * Sets the value of the auditeerimiskohustus property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setAuditeerimiskohustus(java.lang.Boolean value) {
        this.auditeerimiskohustus = value;
    }

    /**
     * Gets the value of the auditeeritus property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public java.lang.Boolean isAuditeeritus() {
        return auditeeritus;
    }

    /**
     * Sets the value of the auditeeritus property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setAuditeeritus(java.lang.Boolean value) {
        this.auditeeritus = value;
    }

    /**
     * Gets the value of the bilansiSisud property.
     * 
     * @return
     *     possible object is
     *     {@link XbrlAruandeBilansiSisud }
     *     
     */
    public XbrlAruandeBilansiSisud getBilansiSisud() {
        return bilansiSisud;
    }

    /**
     * Sets the value of the bilansiSisud property.
     * 
     * @param value
     *     allowed object is
     *     {@link XbrlAruandeBilansiSisud }
     *     
     */
    public void setBilansiSisud(XbrlAruandeBilansiSisud value) {
        this.bilansiSisud = value;
    }

}
