//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xbrlesita_paring complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xbrlesita_paring"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="yldandmed" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}xbrlesita_yldandmed"/&gt;
 *         &lt;element name="sidevahendid" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}xbrlesita_sidevahendid"/&gt;
 *         &lt;element name="osanikud" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}xbrlesita_osanikud"/&gt;
 *         &lt;element name="myygitulu" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}xbrlesita_myygitulu"/&gt;
 *         &lt;element name="manused" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}xbrlesita_dokumendid"/&gt;
 *         &lt;element name="audiitorid" type="{http://producers.arireg.xtee.riik.ee/producer/arireg}xbrlesita_audiitorid" minOccurs="0"/&gt;
 *         &lt;element name="xbrlinfo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xbrlesita_paring", propOrder = {
    "yldandmed",
    "sidevahendid",
    "osanikud",
    "myygitulu",
    "manused",
    "audiitorid",
    "xbrlinfo"
})
public class XbrlesitaParing {

    @XmlElement(required = true)
    protected XbrlesitaYldandmed yldandmed;
    @XmlElement(required = true, nillable = true)
    protected XbrlesitaSidevahendid sidevahendid;
    @XmlElement(required = true, nillable = true)
    protected XbrlesitaOsanikud osanikud;
    @XmlElement(required = true, nillable = true)
    protected XbrlesitaMyygitulu myygitulu;
    @XmlElement(required = true)
    protected XbrlesitaDokumendid manused;
    @XmlElementRef(name = "audiitorid", type = JAXBElement.class, required = false)
    protected JAXBElement<XbrlesitaAudiitorid> audiitorid;
    @XmlElement(required = true, nillable = true)
    protected java.lang.String xbrlinfo;

    /**
     * Gets the value of the yldandmed property.
     * 
     * @return
     *     possible object is
     *     {@link XbrlesitaYldandmed }
     *     
     */
    public XbrlesitaYldandmed getYldandmed() {
        return yldandmed;
    }

    /**
     * Sets the value of the yldandmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link XbrlesitaYldandmed }
     *     
     */
    public void setYldandmed(XbrlesitaYldandmed value) {
        this.yldandmed = value;
    }

    /**
     * Gets the value of the sidevahendid property.
     * 
     * @return
     *     possible object is
     *     {@link XbrlesitaSidevahendid }
     *     
     */
    public XbrlesitaSidevahendid getSidevahendid() {
        return sidevahendid;
    }

    /**
     * Sets the value of the sidevahendid property.
     * 
     * @param value
     *     allowed object is
     *     {@link XbrlesitaSidevahendid }
     *     
     */
    public void setSidevahendid(XbrlesitaSidevahendid value) {
        this.sidevahendid = value;
    }

    /**
     * Gets the value of the osanikud property.
     * 
     * @return
     *     possible object is
     *     {@link XbrlesitaOsanikud }
     *     
     */
    public XbrlesitaOsanikud getOsanikud() {
        return osanikud;
    }

    /**
     * Sets the value of the osanikud property.
     * 
     * @param value
     *     allowed object is
     *     {@link XbrlesitaOsanikud }
     *     
     */
    public void setOsanikud(XbrlesitaOsanikud value) {
        this.osanikud = value;
    }

    /**
     * Gets the value of the myygitulu property.
     * 
     * @return
     *     possible object is
     *     {@link XbrlesitaMyygitulu }
     *     
     */
    public XbrlesitaMyygitulu getMyygitulu() {
        return myygitulu;
    }

    /**
     * Sets the value of the myygitulu property.
     * 
     * @param value
     *     allowed object is
     *     {@link XbrlesitaMyygitulu }
     *     
     */
    public void setMyygitulu(XbrlesitaMyygitulu value) {
        this.myygitulu = value;
    }

    /**
     * Gets the value of the manused property.
     * 
     * @return
     *     possible object is
     *     {@link XbrlesitaDokumendid }
     *     
     */
    public XbrlesitaDokumendid getManused() {
        return manused;
    }

    /**
     * Sets the value of the manused property.
     * 
     * @param value
     *     allowed object is
     *     {@link XbrlesitaDokumendid }
     *     
     */
    public void setManused(XbrlesitaDokumendid value) {
        this.manused = value;
    }

    /**
     * Gets the value of the audiitorid property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XbrlesitaAudiitorid }{@code >}
     *     
     */
    public JAXBElement<XbrlesitaAudiitorid> getAudiitorid() {
        return audiitorid;
    }

    /**
     * Sets the value of the audiitorid property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XbrlesitaAudiitorid }{@code >}
     *     
     */
    public void setAudiitorid(JAXBElement<XbrlesitaAudiitorid> value) {
        this.audiitorid = value;
    }

    /**
     * Gets the value of the xbrlinfo property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getXbrlinfo() {
        return xbrlinfo;
    }

    /**
     * Sets the value of the xbrlinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setXbrlinfo(java.lang.String value) {
        this.xbrlinfo = value;
    }

}
