//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for x_isikuroll.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="x_isikuroll"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AJPH"/&gt;
 *     &lt;enumeration value="S"/&gt;
 *     &lt;enumeration value="A"/&gt;
 *     &lt;enumeration value="D"/&gt;
 *     &lt;enumeration value="DOKH"/&gt;
 *     &lt;enumeration value="ERIH"/&gt;
 *     &lt;enumeration value="ESIS"/&gt;
 *     &lt;enumeration value="EUSOS"/&gt;
 *     &lt;enumeration value="ESOI"/&gt;
 *     &lt;enumeration value="ETTEV"/&gt;
 *     &lt;enumeration value="VFILJ"/&gt;
 *     &lt;enumeration value="FIE"/&gt;
 *     &lt;enumeration value="JUHA"/&gt;
 *     &lt;enumeration value="JUHE"/&gt;
 *     &lt;enumeration value="JUHL"/&gt;
 *     &lt;enumeration value="JUHJ"/&gt;
 *     &lt;enumeration value="JPNKR"/&gt;
 *     &lt;enumeration value="LIKV"/&gt;
 *     &lt;enumeration value="YHLLV"/&gt;
 *     &lt;enumeration value="MORAH"/&gt;
 *     &lt;enumeration value="LIKVJ"/&gt;
 *     &lt;enumeration value="N"/&gt;
 *     &lt;enumeration value="E"/&gt;
 *     &lt;enumeration value="O"/&gt;
 *     &lt;enumeration value="PANTP"/&gt;
 *     &lt;enumeration value="PANKR"/&gt;
 *     &lt;enumeration value="P"/&gt;
 *     &lt;enumeration value="PROK"/&gt;
 *     &lt;enumeration value="R"/&gt;
 *     &lt;enumeration value="TOSAN"/&gt;
 *     &lt;enumeration value="UOSAN"/&gt;
 *     &lt;enumeration value="SJESI"/&gt;
 *     &lt;enumeration value="YHL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "x_isikuroll")
@XmlEnum
public enum XIsikuroll {

    AJPH,
    S,
    A,
    D,
    DOKH,
    ERIH,
    ESIS,
    EUSOS,
    ESOI,
    ETTEV,
    VFILJ,
    FIE,
    JUHA,
    JUHE,
    JUHL,
    JUHJ,
    JPNKR,
    LIKV,
    YHLLV,
    MORAH,
    LIKVJ,
    N,
    E,
    O,
    PANTP,
    PANKR,
    P,
    PROK,
    R,
    TOSAN,
    UOSAN,
    SJESI,
    YHL;

    public java.lang.String value() {
        return name();
    }

    public static XIsikuroll fromValue(java.lang.String v) {
        return valueOf(v);
    }

}
