//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.29 at 08:17:10 PM EEST 
//


package ee.rik.kris5.xroad.model.soap;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for x_omandiliik.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="x_omandiliik"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="L"/&gt;
 *     &lt;enumeration value="K"/&gt;
 *     &lt;enumeration value="Y"/&gt;
 *     &lt;enumeration value="LIHT"/&gt;
 *     &lt;enumeration value="KAAS"/&gt;
 *     &lt;enumeration value="YHIS"/&gt;
 *     &lt;enumeration value="X"/&gt;
 *     &lt;enumeration value="KAASYHIS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "x_omandiliik")
@XmlEnum
public enum XOmandiliik {

    L,
    K,
    Y,
    LIHT,
    KAAS,
    YHIS,
    X,
    KAASYHIS;

    public java.lang.String value() {
        return name();
    }

    public static XOmandiliik fromValue(java.lang.String v) {
        return valueOf(v);
    }

}
