spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KRIS-Five/arch-concept-config
        native:
          search-locations: classpath:/shared

server:
  port: 8888

security:
  user:
    password: pass